name: GitHub Minutes Report Curl

on:
  # runs when one of the defined wfs are completed
  workflow_run:
    workflows: [Test WF, Another Test WF] # To do: Get all workflows from Repo and include them here
    types:
      - completed

jobs:
  # This step gets the timing for each wf via GitHub API request
  updateWorkflowTimings:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        WFs: [test.yml, another_test.yml]
    steps:
      - name: Get latest timing from GitHub API
        uses: octokit/request-action@v2.1.0
        id: get_latest_timing
        with:
          route: GET /repos/${{ github.repository }}/actions/workflows/${{ matrix.WFs }}/timing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output response check
        run: echo ${{ toJSON(fromJSON(steps.get_latest_timing.outputs.data).billable.UBUNTU.total_ms) }}

      - name: Post latest timing to Datatdog
        id: post_latest_timing
        run: |
          ## Dynamic Points
          # Post time-series data that can be graphed on Datadogâ€™s dashboards.
          # Template variables
          export NOW="$(date +%s)"
          # Curl command
          curl -X POST "https://api.datadoghq.eu/api/v1/series" \
          -H "Content-Type: text/json" \
          -H "DD-API-KEY: $DD_API_KEY" \
          -d @- << EOF
          {
            "series": [
              {
                "metric": "github.actions.minutes",
                "points": [[${NOW}, $latest_total_ms_ubuntu]],
                "tags": $tag_workflow_id
              }
            ]
          }
          EOF
        env:
          # Datadog API and Application Keys (stored in GitHub Actions Secrets)
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DD_APP_KEY: ${{ secrets.DATADOG_APPLICATION_KEY }}
          # Values from previous steps
          latest_total_ms_ubuntu: ${{ toJSON(fromJSON(steps.get_latest_timing.outputs.data).billable.UBUNTU.total_ms) }}
          tag_workflow_id: ${{ matrix.WFs }}